// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSVv02nxQ42QMQydEGwCBmwXi8T71yNg',
    appId: '1:646674176452:web:66fb1450641eadc3d12c91',
    messagingSenderId: '646674176452',
    projectId: 'profile-page-ba70a',
    authDomain: 'profile-page-ba70a.firebaseapp.com',
    storageBucket: 'profile-page-ba70a.appspot.com',
    databaseURL: 'https://clubhouses-75ddb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGTMpN9BgPLW8InzGelMm9laprieS7Do',
    appId: '1:646674176452:android:e36d100dd115352ad12c91',
    messagingSenderId: '646674176452',
    projectId: 'profile-page-ba70a',
    storageBucket: 'profile-page-ba70a.appspot.com',
    databaseURL: 'https://clubhouses-75ddb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNTOyZq9huQXoQZ5oRgx1eGskdOd31jvU',
    appId: '1:646674176452:ios:28e671fc8200202ad12c91',
    messagingSenderId: '646674176452',
    projectId: 'profile-page-ba70a',
    storageBucket: 'profile-page-ba70a.appspot.com',
    iosClientId: '646674176452-48upl9nh4d028gbmqb4g7f2qpbs6itk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
    databaseURL: 'https://clubhouses-75ddb-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNTOyZq9huQXoQZ5oRgx1eGskdOd31jvU',
    appId: '1:646674176452:ios:28e671fc8200202ad12c91',
    messagingSenderId: '646674176452',
    projectId: 'profile-page-ba70a',
    storageBucket: 'profile-page-ba70a.appspot.com',
    iosClientId: '646674176452-48upl9nh4d028gbmqb4g7f2qpbs6itk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
    databaseURL: 'https://clubhouses-75ddb-default-rtdb.firebaseio.com/',
  );
}
